import React from 'react';
import type { Metadata } from 'next';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { FileText, Scale, CheckCircle2, AlertTriangle, ShieldCheck } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms & Conditions — Terms of Service & License',
  description: 'Review BG Remover’s Terms and Conditions. Free commercial and personal license with 100% user content ownership and zero restrictions.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col justify-between bg-[#fafafa] text-[#171717] selection:bg-zinc-950 selection:text-white">
      <div>
        <Header />

        <main className="max-w-4xl mx-auto px-4 py-12 sm:py-16">
          
          {/* Eyebrow Badge */}
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-zinc-100 border border-zinc-200 text-zinc-900 text-xs font-mono-tech mb-6 shadow-vercel-sm">
            <Scale className="w-3.5 h-3.5 text-zinc-950" />
            <span>TERMS OF SERVICE</span>
          </div>

          <h1 className="text-3xl sm:text-5xl font-bold tracking-tight text-zinc-950 mb-4">
            Terms & Conditions.
          </h1>

          <p className="text-zinc-600 text-sm sm:text-base mb-10 leading-relaxed">
            Effective Date: {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}
          </p>

          <div className="prose prose-zinc max-w-none space-y-8 text-xs sm:text-sm text-zinc-700 leading-relaxed">
            
            {/* Section 1: Acceptance & License */}
            <section className="bg-white p-6 sm:p-8 rounded-2xl border border-zinc-200 shadow-vercel-sm">
              <div className="flex items-center gap-3 mb-4">
                <CheckCircle2 className="w-5 h-5 text-zinc-950" />
                <h2 className="text-xl font-bold text-zinc-950 m-0">1. Free License & Permitted Use</h2>
              </div>
              <p>
                BG Remover provides a free web-based tool for personal, educational, creative, and commercial use. You are granted a non-exclusive, worldwide, royalty-free license to use BG Remover to process images, remove backgrounds, customize backdrops, and download output transparent PNG, JPG, WebP, or SVG files.
              </p>
            </section>

            {/* Section 2: Intellectual Property */}
            <section className="bg-white p-6 sm:p-8 rounded-2xl border border-zinc-200 shadow-vercel-sm">
              <div className="flex items-center gap-3 mb-4">
                <ShieldCheck className="w-5 h-5 text-zinc-950" />
                <h2 className="text-xl font-bold text-zinc-950 m-0">2. 100% User Content Ownership</h2>
              </div>
              <p>
                You retain <strong>100% ownership and copyright</strong> of all original images uploaded to BG Remover and all output files generated by our tool. BG Remover claims no intellectual property rights, ownership, or licensing rights over your images or derivative cutouts.
              </p>
            </section>

            {/* Section 3: Acceptable Conduct */}
            <section className="bg-white p-6 sm:p-8 rounded-2xl border border-zinc-200 shadow-vercel-sm">
              <div className="flex items-center gap-3 mb-4">
                <AlertTriangle className="w-5 h-5 text-zinc-950" />
                <h2 className="text-xl font-bold text-zinc-950 m-0">3. Acceptable Use Policy</h2>
              </div>
              <p>
                You agree not to use BG Remover to process content that violates applicable copyright laws, infringes on third-party trademarks, or promotes illegal activities. You are solely responsible for ensuring you possess appropriate usage rights for any images you process.
              </p>
            </section>

            {/* Section 4: Limitation of Liability */}
            <section className="bg-white p-6 sm:p-8 rounded-2xl border border-zinc-200 shadow-vercel-sm">
              <div className="flex items-center gap-3 mb-4">
                <FileText className="w-5 h-5 text-zinc-950" />
                <h2 className="text-xl font-bold text-zinc-950 m-0">4. Disclaimer & Limitation of Liability</h2>
              </div>
              <p>
                BG Remover is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind. While we strive to maintain sub-second AI accuracy and zero downtime, BG Remover is not liable for any indirect or consequential damages arising from the use or inability to use our software service.
              </p>
            </section>

          </div>

        </main>
      </div>

      <Footer />
    </div>
  );
}
